### ISSUE TITLE
Is there a document to instruct the project?

### ISSUE THREAD

**Issue by willard-yuan** [Sundo/Imse#1]
Hi, Sundo
I'm interested in this project, but there is no document to instruct it. Can you write something to install or configure how to run the project?

**Comment by Sundo** [comment]
Hi,

Unfortunately the project is still quite unfinished and we haven't made a clean easy-to-use version. Given the priorities around here at the moment, I'm not sure when (or if) that's going to happen. At least I'm working on different kernel functions for the GP rather than cleaning up the code, even though I try to do some cleaning while at it.

In other words, there's no easy way to run the project at the moment. If you are intrested in the Gaussian process part, running that might be easier since it's a separate process which you can run and it communicates using SimpleXMLRPCServer. The initial commit GPU version should work, but the CPU code is lagging a bit behind.

To run it you'll need at least:
cuda toolkit
pycuda
numpy and scipy
scikits-learn

I'll try to get the Gaussian process code for both GPU and CPU cleaned up and documented in near future, but can't really say whether the whole project in it's current form will ever get there.
